# Generated by Django 4.0.4 on 2022-07-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CosineSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('link', models.CharField(max_length=120)),
                ('score', models.TextField()),
                ('angle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WebSearching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('link', models.CharField(max_length=120)),
                ('text', models.TextField(default='')),
            ],
        ),
    ]
